### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nachocifu** [Matuteale/final-project#1]
A corregir:

- [x] 1) Emprolijar los capítulos 4 y 5 para que estén más ordenados y que estén un poco más sólidos en lo que detallan.
- [x] 2) Denle una mirada a algún apunte o video de internet de lo que es Machine Learning para clarificar cómo dividen las cosas:
- [x] Cómo es el dataset que usan, cómo está dividido, qué métricas usan, como validaron los resultados que obtuvieron.

- [x] En la discusión pueden también incluir información sobre limitaciones de lo que probaron.
- [x]  Hagan algún gráfico del prototipo, pongan la foto del Neurosky.
- [x] 4) Sería interesante que en el capítulo 3 mencionen casos concretos de empresas tecnológicas de salud de rehabilitación. Eso les va a permitir expandir un poco más ese capítulo. 
- [x] 5) Este capítulo (4) requiere introducción. 
- [x] Fijense que hablan de la vincha sin haber explicado que es. 
- [x] Intenten poner acá una intro sobre Design Thinking, creación de elementos iterativos. 
- [x] Enganchen eso con la idea de tener algo que pueda servir para el tema del financiamiento. 
- [x] Tienen que contar que lo que intentar es armar un estudio de factibilidad. 
- [x] Cuenten por qué usan el Neurosky.
- [x] Agreguen una foto y pongan también el detalle técnico con una tabla.
- [x] En el caso de ustedes ya lo tenían pero pongan que sirve por el lado de que es de costo bajo y tiene un set up rápido.
- [x] Hagan un gráfico de la arquitectura de los componentes que después describen uno tras otro.  
- [x] En el 4.2.2 hagan una intro de Machine Learning, del pipeline de procesamiento y de qué utilizan para cada parte (Preprocesamiento + Feature Extraction + Clasificador).   
- [x] Luego tienen que detallar cada una de esas partes cómo las resuelven, qué parametros tienen.  
- [x] Lo tienen que escribir como si alguien lo fuese a reproducir. 
- [x] Expliquen regresión logística brevemente con alguna fórmula y ponen la referencia de dónde la sacaron.
  - [x] ? En este capítulo tienen que aclarar bien cómo sería el producto que ustedes se imaginan el prototípo desde los aspectos del hardware, del producto.  
- [x] Ahí tienen mucho para escribir también, acuerdense que la idea es que ustedes hagan una especie de análisis de factibilidad, hablen de alternativas similares (simplemente fijense otras alternativas y pongan cuál podrían ustedes elegir y por qué).
- [x] 6) Definan qué quieren decir con "buffer" porque no es un término muy usado en ML. 
- [x]  Quizás eso les convenga ponerlo en la sección 4. 
- [x]  Los gráficos tienen que achicarlos cuando ponen varios, tienen que incluir un epígrafe debajo que explique cada gráfico (o cuando son varios en grillas de NxN uno abajo de todo que explique una generalidad de todos y puntualice uno a uno qué tiene tipo (a) bla bla bla (b) bla bla bla ). 
 - [x] Cuando este terminada la parte de resultados ordenar a mano los graficos para que las paginas queden bien separadas
 - [x] El 5.0.1. tienen que explicar en algún lugar que es "Máxima diferencia en buffer" ??
 - [x] Aclaren bien qué métrica usan para medir la performance, cómo la miden.  
 - [x] Intenten agregar y completar matrices de confusión, ROC y especifiquen bien cómo hicieron convalidación cruzada y la separación de los datos entre entrenamiento y test.
- [x] 7) Tienen que comparar un poco los resultados contra resultados obtenidos en otros trabajos o con sistemas similares. 
 - [x] Fijense en papers similares qué resultados obtienen y realizan una comparación rápida de los resultados que obtuvieron.  
  P Cuando arrancan cada capítulo ponganlo en un punto aparte en una hoja nueva.

Presentación:
Traten ahora de ir armando el bosquejo de la presentación de 30 minutos. 
- [ ] Les digo esto porque les va a servir para ver qué ponen en el propio informe ahora.  
- [ ]  En esos 30 minutos tienen que presentar lo más sustancial de su trabajo, y lo tienen que hacer ante el jurado, otros profesores, y eventualmente sus familiares.  
- [ ] Será online.
- [ ]  La presentación es como una obra de teatro, es un "show educado".  
- [ ] Tiene que tener un nudo, donde plantean el problema mundial que motiva esto.  
- [ ] Luego plantean las soluciones existentes y van especificando la problemática hasta que llegan a un problema donde lo que ustedes hicieron es la solución.    
- [ ]  Luego plantean el meollo de la cuestión, siempre jugando con que las cosas no salen no salen, hasta que cuentan cómo resolvieron algo, presentan la problemática de financiamiento, su prototipo, los experimentos que hicieron, los resultados que obtuvieron interpretados (eso es la discusión en el informe) y sobre todo las recomendaciones a futuro.

**Comment by Matuteale** [comment]
- [x] 1-Intro: intenten incrementar lo que detallan de la sección 2.6 y escriban menos de la sección 2.1,2.2, y 2.3.  Por ejemplo en el caso de ustedes no hace falta que detallen tanto Magnetoencefalografía, basta con una oración y listo (y si hace falta que detallen bien AAC).
- [x] 3- Pongan una breve intro de por qué está ese capítulo ahí.  Pueden poner un pequeño párrafo y después poner "Financiamiento en Argentina" y ahí lo empalman con lo que ya tienen.
- [x] 3.4- Cambien el título de Conclusiones a "Recomendaciones".
- [x] 4.3- Cambien el nombre "buffer circular" x "ventana deslizante circular".
- [x] 5- Definan bien que longitud tienen los features que compusieron, cuántos datos les quedan en el dataset para cada persona, cuánto usan para traning y testing.
- [x] 5- Cambien "factores" x "vectores característicos" o directamente "features".
- [x] No me queda claro donde detallan que hicieron con la información de la cámara, ni tampoco cómo usaron eso para marcar bien el dataset para poder tener bien identificado en qué momentos ocurrían los pestañeos y que eso les servía después para anotar los lugares donde ocurrían los pestañeos.

Corrijan esto y leanlo mucho varias veces para ver de iterar y corregír pequeños errores que pueden haber quedado.  Después de eso ya se lo pueden enviar a Valeria para que se los mande a los Jurados.
